"""Foliage categories."""

FOLIAGE_TYPES = [
    "brevideciduous",
    "deciduous",
    "evergreen",
    "broadleaf-evergreen",
    "marcescence"
]
FOLIAGE_ARRANGEMENT_TYPES = [
    'whorled',
    'alternate',
    'spiral',
    'opposite',
]
FOLIAGE_MORPHOLOGY_TYPES = [
    # Simple
    "ovate",
    "linear",
    "peltate",
    "hastate",
    "cordate",
    "reniform",
    "orbiculate",
    "spatulate",
    "lanceolate",
    "undulate",
    "sinuate",
    "serrate",
    "dentate",
    "lobate",
    "scalloped",
    "palmate",
    "digitate",
    "palmapartite",
    "pinnapartite",
    "pinnatifid",
    # Compound-pinnate
    "unipinnate",
    "geminate-pinnate",
    "tetrapinnate",
    "tripinnate",
    "bipinnate",
    "paripinnate",
    "imparipinnate",
    "alternipinnate",
    "pinnately-lobed",
    "pinnately-cleft",
    "pinnately-cleft",
    "pinnately-divided",
    "pinnately-trifoliate",
    "palmately-trifoliate",
    "biternate",
    "palmatisect",
    "palmatibolate",
    "pedate",
    "bipartite",
    "tripartite",
    "bipinnatisect",
    "tripinnatisect",
    "pinnatisect",
]
