"""Schema proposal.

# TODO: https://en.wikipedia.org/wiki/Glossary_of_botanical_terms
# https://en.wikipedia.org/wiki/Dehiscence_(botany)
# All of that would be supremely useful.

Ways to organize information:

1. Giant document
    - nested
    - flat

2. Tables based on fully normalized traditional SQL design
    (1st, 2nd, 3rd normal form).

3. Tables with core information, then join tables with an medium level of
    denormalization to make queries simpler.

    e.g. categories like:

    - botany
    - landscaping
    - horticulture
    - genetics
    - etc
"""

from plantstuff.db import foliage, locales, taxonomy


SOIL_PH_TOLERANCE_MAX_RANGE = [
    "3.5-3.6",
    "3.7-3.8",
    "3.9-4",
    "4.1-4.2",
    "4.3-4.4",
    "4.5-4.6",
    "4.7-4.8",
    "4.9-5",
    "5.1-5.2",
    "5.3-5.4",
    "5.5-5.6",
    "5.7-5.8",
    "5.9-6",
    "6.1-6.2",
    "6.3-6.4",
    "6.5-6.6",
    "6.7-6.8",
    "6.9-7",
    "7.1-7.2",
    "7.3-7.4",
    "7.5-7.6",
    "7.7-7.8",
    "7.9-8",
    "8.1-8.2",
    "8.3-8.4",
    "8.5-8.6",
    "8.7-8.8",
    "8.9-9",
    "9.1-9.2",
    "9.3-9.4",
    "9.5-9.6",
    "9.7-9.8",
    "9.9-10",
    "10.1"
]

# Precipitation
PRECIPATION_TOLERANCE_MAX_RANGE = [
    "10-14",
    "15-19",
    "20-24",
    "25-29",
    "30-39",
    "40-49",
    "50-59",
    "60-79",
    "80-99",
    "100-149",
    "150-199",
    ">=200"
]
PRECIPATION_TOLERANCE_MIN_RANGE = [
    "0-4",
    "5-9",
    "10-14",
    "15-19",
    "20-24",
    "25-29",
    "30-39",
    "40-49",
    "50-59",
    ">=60"
]
ROOT_DEPTH_MIN_RANGE = [
    "1-2",
    "3-5",
    "6-8",
    "9-11",
    "12-14",
    "15-17",
    "18-20",
    "21-23",
    "24-26",
    "27-29",
    "30-32",
    "33-35",
    "36-38",
    "39-41",
    "42-44",
    "45-47",
    "48-51",
    "52-120"
]
GROWTH_FORMS = [
    "climbing",
    "columnar",
    "conical",
    "decumbent",
    "erect",
    "irregular",
    "oval",
    "prostrate",
    "rounded",
    "semi-erect",
    "vase"
]
{
    "palatable_animl_brs_condition": [
        "low",
        "medium",
        "high"
    ],
    "synonyms": [
        "accepted names and synonyms",
        "accepted names only"
    ],
    "soil_adp_c_txt_ind": [
        "yes",
        "no"
    ],
    "post_suit_ind": [
        "yes",
        "no"
    ],
    "plantguide_ind": [
        "only with plant guides",
        "only without plant guides"
    ],
    "folg_color_condition": [
        "dark green",
        "green",
        "gray-green",
        "red",
        "white-gray",
        "yellow-green"
    ],
    "slin_tolerance_condition": [
        "none",
        "low",
        "medium",
        "high"
    ],
    "family_sym": [
        "acanth",
        "acaros",
        "acerac",
        "achato",
        "acorac",
        "acrobo",
        "actini",
        "adeloc",
        "adoxac",
        "agavac",
        "agyria",
        "aizoac",
        "alecto",
        "alisma",
        "alliso",
        "aloace",
        "amaran",
        "amblys",
        "anacar",
        "andrea",
        "andrea2",
        "anemia",
        "aneura",
        "annona",
        "anomod",
        "anthel",
        "anthoc",
        "apiace",
        "apocyn",
        "aponog",
        "aquifo",
        "aracea",
        "aralia",
        "arauca",
        "archid",
        "arctom",
        "arecac",
        "aristo",
        "arnell",
        "arthon",
        "arthop",
        "arthro",
        "asclep",
        "asplen",
        "astera",
        "astero",
        "atheli",
        "aulaco",
        "aytoni",
        "azolla",
        "bacidi",
        "baeomy",
        "balano",
        "balsam",
        "bartra",
        "basell",
        "batace",
        "begoni",
        "berber",
        "betula",
        "biator",
        "bignon",
        "bixace",
        "blasia",
        "blechn",
        "bombac",
        "boragi",
        "brachy",
        "brassi",
        "brigan",
        "bromel",
        "bruchi",
        "brunel",
        "bryace",
        "bryoxi",
        "buddle",
        "burman",
        "burser",
        "butoma",
        "buxace",
        "buxbau",
        "cabomb",
        "cactac",
        "calici",
        "callic",
        "callit",
        "calyca",
        "calyce",
        "calymp",
        "calypo",
        "campan",
        "candel",
        "canell",
        "cannab",
        "cannac",
        "capnod",
        "cappar",
        "caprif",
        "carica",
        "caryoc",
        "caryop",
        "casuar",
        "catill",
        "catosc",
        "cauler",
        "cecrop",
        "celast",
        "cephal",
        "cephal2",
        "cephal3",
        "cerato",
        "cercid",
        "chenop",
        "chiono",
        "chlora",
        "chonec",
        "chryso",
        "chryso2",
        "cistac",
        "cladon",
        "clavar",
        "clethr",
        "clevea",
        "climac",
        "clusia",
        "coccoc",
        "coccot",
        "collem",
        "combre",
        "commel",
        "conioc",
        "connar",
        "conoce",
        "convol",
        "cornac",
        "corsin",
        "cortic",
        "coryno",
        "costac",
        "crassu",
        "crocyn",
        "crosso",
        "crypha",
        "cucurb",
        "cunoni",
        "cupres",
        "cuscut",
        "cyathe",
        "cycada",
        "cyclan",
        "cymodo",
        "cypera",
        "cyrill",
        "dacamp",
        "dactyl",
        "dalton",
        "datisc",
        "davall",
        "dendro",
        "dennst",
        "diapen",
        "dickso",
        "dicran",
        "dillen",
        "diosco",
        "dipsac",
        "dipter",
        "discel",
        "ditric",
        "droser",
        "dryopt",
        "ebenac",
        "ectole",
        "eigler",
        "elaeag",
        "elaeoc",
        "elatin",
        "empetr",
        "encaly",
        "entodo",
        "epacri",
        "ephedr",
        "epheme",
        "equise",
        "eremol",
        "ericac",
        "erioca",
        "erpodi",
        "erythr",
        "euphor",
        "fabace",
        "fabron",
        "fagace",
        "fissid",
        "flacou",
        "flagel",
        "fontin",
        "fossom",
        "fouqui",
        "franke",
        "fumari",
        "funari",
        "fuscid",
        "garrya",
        "gentia",
        "geocal",
        "gerani",
        "gesner",
        "gigasp",
        "ginkgo",
        "gleich",
        "gnetac",
        "gomphi",
        "gooden",
        "gracil",
        "grammi",
        "graphi",
        "greyia",
        "grimmi",
        "grossu",
        "gunner",
        "gyalec",
        "gymnom",
        "gypsop",
        "gyroth",
        "haemat",
        "haemod",
        "halora",
        "halyme",
        "hamame",
        "hangua",
        "haplom",
        "hedwig",
        "helico",
        "helodi",
        "heppia",
        "herber",
        "hernan",
        "hippoc",
        "hippoc2",
        "hippur",
        "hooker",
        "hydran",
        "hydroc",
        "hydrop",
        "hyloco",
        "hymene",
        "hymeno",
        "hypnac",
        "hypocr",
        "hypopt",
        "icacin",
        "illici",
        "iridac",
        "isoeta",
        "joinvi",
        "jubula",
        "juglan",
        "juncac",
        "juncag",
        "junger",
        "kramer",
        "lamiac",
        "lardiz",
        "laurac",
        "lecano",
        "lecide",
        "lecyth",
        "leitne",
        "lejeun",
        "lemnac",
        "lennoa",
        "lentib",
        "leotia",
        "lepido",
        "leptod",
        "leskea",
        "letrou",
        "leucob",
        "leucod",
        "lichen",
        "lichin",
        "liliac",
        "limnan",
        "limnoc",
        "linace",
        "loasac",
        "lobari",
        "logani",
        "lophos",
        "lorant",
        "lunula",
        "lycopo",
        "lygodi",
        "lythra",
        "magnol",
        "malpig",
        "malvac",
        "marant",
        "maratt",
        "marcgr",
        "marcha",
        "marsil",
        "mastig",
        "mastod",
        "mayaca",
        "meesia",
        "megalo",
        "melano",
        "melasp",
        "melast",
        "meliac",
        "melian",
        "menisp",
        "menyan",
        "mesopt",
        "meteor",
        "metzge",
        "micare",
        "microc",
        "mniace",
        "mollug",
        "monimi",
        "monobl",
        "monoso",
        "monotr",
        "morace",
        "moring",
        "musace",
        "mycobl",
        "mycoca",
        "mycopo",
        "mycosp",
        "myopor",
        "myrica",
        "myrini",
        "myrist",
        "myrsin",
        "myrtac",
        "myxotr",
        "najada",
        "necker",
        "nelumb",
        "nepent",
        "nephro",
        "nototh",
        "nyctag",
        "nympha",
        "ochnac",
        "odonto",
        "oedipo",
        "olacac",
        "oleace",
        "onagra",
        "opegra",
        "ophiog",
        "ophiop",
        "orchid",
        "oroban",
        "orthot",
        "osmund",
        "oxalid",
        "oxymit",
        "paeoni",
        "pallav",
        "pandan",
        "pannar",
        "papave",
        "parker",
        "parmel",
        "passif",
        "pedali",
        "pellia",
        "peltig",
        "peltul",
        "pertus",
        "philyd",
        "phlyct",
        "phylla",
        "physci",
        "phytol",
        "piloca",
        "pinace",
        "pipera",
        "pittos",
        "placyn",
        "plagio",
        "plagio2",
        "planta",
        "platan",
        "platyg",
        "pleoma",
        "pleosp",
        "pleuro",
        "pleuro2",
        "plumba",
        "poacea",
        "podoca",
        "podost",
        "polemo",
        "polyga",
        "polygo",
        "polypo",
        "polytr",
        "ponted",
        "porell",
        "porpid",
        "portul",
        "posido",
        "potamo",
        "pottia",
        "primul",
        "protea",
        "protot",
        "pseudo",
        "pseudo2",
        "psilot",
        "psorac",
        "pterid",
        "pterig",
        "pterob",
        "ptilid",
        "ptycho",
        "punica",
        "pyreno",
        "pyrenu",
        "pyrola",
        "racopi",
        "radula",
        "raffle",
        "ramali",
        "ranunc",
        "reseda",
        "rhachi",
        "rhamna",
        "rhizoc",
        "rhizog",
        "rhizop",
        "rhytid",
        "riccia",
        "riella",
        "rimula",
        "roccel",
        "rosace",
        "rubiac",
        "ruppia",
        "rutace",
        "sabiac",
        "salica",
        "salvin",
        "santal",
        "sapind",
        "sapota",
        "sarrac",
        "saurur",
        "saxifr",
        "scapan",
        "schaer",
        "scheuc",
        "schisa",
        "schist",
        "schiza",
        "scoule",
        "scroph",
        "selagi",
        "selige",
        "semato",
        "simaro",
        "simmon",
        "smilac",
        "solana",
        "solori",
        "sonner",
        "sparga",
        "sphaer",
        "sphaer2",
        "sphagn",
        "spheno",
        "sphinc",
        "splach",
        "splach2",
        "stackh",
        "staphy",
        "stemon",
        "stercu",
        "stereo",
        "stereo2",
        "sticti",
        "streli",
        "strigu",
        "styrac",
        "surian",
        "symplo",
        "syzygo",
        "taccac",
        "tamari",
        "targio",
        "taxace",
        "telosc",
        "tetrap",
        "thamno",
        "theace",
        "thelen",
        "thelia",
        "thelot",
        "thelyp",
        "theoph",
        "thromb",
        "thuidi",
        "thymel",
        "tiliac",
        "timmia",
        "trapac",
        "trapel",
        "tremel",
        "treubi",
        "tricho",
        "tricho2",
        "tricho3",
        "tricho4",
        "triuri",
        "tropae",
        "trypet",
        "turner",
        "typhac",
        "ulmace",
        "ulvace",
        "umbili",
        "uncerta",
        "uncertb",
        "urtica",
        "valeri",
        "verben",
        "verruc",
        "vezdae",
        "violac",
        "viscac",
        "vitace",
        "vittar",
        "winter",
        "xyrida",
        "zamiac",
        "zannic",
        "zingib",
        "zoster",
        "zygoph"
    ],
    "vs_comm_avail": [
        "no known source",
        "routinely available",
        "contracting only",
        "field collections only"
    ],
    "nurs_stk_suit_ind": [
        "yes",
        "no"
    ],
    "epithet_rank": [
        "only genus epithet",
        "only species epithet",
        "only subspecies epithet",
        "only variety epithet",
        "only subvariety epithet",
        "only forma epithet"
    ],
    "prpg_sprig_ind": [
        "yes",
        "no"
    ],
    "nat_wet_ind": [
        "with wetland status",
        "--obl (obligate wetland)",
        "--obl? (possibly obligate wetland)",
        "--facw+ (facultative wetland+)",
        "--facw+? (possibly facultative wetland+)",
        "--facw (facultative wetland)",
        "--facw? (possibly facultative wetland)",
        "--facw- (facultative wetland-)",
        "--facw-? (possibly facultative wetland-)",
        "--fac+ (facultative+)",
        "--fac+? (possibly facultative+)",
        "--fac (facultative)",
        "--fac? (possibly facultative)",
        "--fac- (facultative-)",
        "--fac-? (possibly facultative-)",
        "--facu+ (facultative upland+)",
        "--facu (facultative upland)",
        "--facu? (possibly facultative upland)",
        "--facu- (facultative upland-)",
        "--upl (obligate upland)",
        "without wetland status (upland plants)"
    ],
    "temp_tolerance_min_range": [
        "-75--53",
        "-52--48",
        "-47--43",
        "-42--38",
        "-37--33",
        "-32--28",
        "-27--23",
        "-22--18",
        "-17--13",
        "-12--8",
        "-7--3",
        "-2-2",
        "3-7",
        "8-12",
        "13-17",
        "18-22",
        "23-27",
        "28-32",
        "33-37",
        "38-42",
        "43-47",
        "48-52",
        "53-57",
        "58-62",
        "63-67",
        "68-71",
        "72-75"
    ],
    "drght_tolerance_condition": [
        "none",
        "low",
        "medium",
        "high"
    ],
    "author_ranks": [
        "only genus author",
        "only species author",
        "only subspecies author",
        "only variety author",
        "only subvariety author",
        "only forma author"
    ],
    "flwr_cspc_ind": [
        "yes",
        "no"
    ],
    "plywd_vnr_suit_ind": [
        "yes",
        "no"
    ],
    "frut_seed_abund_condition": [
        "none",
        "low",
        "medium",
        "high"
    ],
    "foddr_suit_ind": [
        "yes",
        "no"
    ],
    "state_te_status": [
        "with state status",
        "--arizona",
        "--arkansas",
        "--california",
        "--connecticut",
        "--florida",
        "--georgia",
        "--illinois",
        "--indiana",
        "--iowa",
        "--kentucky",
        "--maine",
        "--maryland",
        "--massachusetts",
        "--michigan",
        "--minnesota",
        "--missouri",
        "--nebraska",
        "--nevada",
        "--new hampshire",
        "--new jersey",
        "--new mexico",
        "--new york",
        "--north carolina",
        "--ohio",
        "--oregon",
        "--pennsylvania",
        "--puerto rico",
        "--rhode island",
        "--tennessee",
        "--texas",
        "--vermont",
        "--virginia",
        "--washington",
        "--wisconsin",
        "without state status"
    ],
    "prpg_sod_ind": [
        "yes",
        "no"
    ],
    "frut_seed_prst_ind": [
        "yes",
        "no"
    ],
    "veg_sprd_rate_condition": [
        "none",
        "slow",
        "moderate",
        "rapid"
    ],
    "fert_rqmt_condition": [
        "low",
        "medium",
        "high"
    ],
    "lfspn_condition": [
        "short",
        "moderate",
        "long"
    ],
    "cold_strat_ind": [
        "yes",
        "no"
    ],
    "nativestatuscode": [
        "native to plants floristic area",
        "--north america native",
        "\u00a0\u00a0--l48 native",
        "\u00a0\u00a0--ak native",
        "\u00a0\u00a0--can native",
        "\u00a0\u00a0--gl native",
        "\u00a0\u00a0--spm native",
        "--hi native",
        "--pr native",
        "--vi native",
        "introduced to plants floristic area",
        "--north america introduced",
        "\u00a0\u00a0--l48 introduced",
        "\u00a0\u00a0--ak introduced",
        "\u00a0\u00a0--can introduced",
        "\u00a0\u00a0--gl introduced",
        "\u00a0\u00a0--spm introduced",
        "--hi introduced",
        "--pr introduced",
        "--vi introduced"
    ],
    "state_nox_status": [
        "with state status",
        "--alaska",
        "--alabama",
        "--arkansas",
        "--arizona",
        "--california",
        "--colorado",
        "--connecticut",
        "--delaware",
        "--florida",
        "--hawaii",
        "--iowa",
        "--idaho",
        "--illinois",
        "--indiana",
        "--kansas",
        "--kentucky",
        "--louisiana",
        "--massachusetts",
        "--maryland",
        "--maine",
        "--michigan",
        "--minnesota",
        "--missouri",
        "--mississippi",
        "--montana",
        "--north carolina",
        "--north dakota",
        "--nebraska",
        "--new hampshire",
        "--new mexico",
        "--nevada",
        "--ohio",
        "--oklahoma",
        "--oregon",
        "--pennsylvania",
        "--south carolina",
        "--south-dakota",
        "--tennessee",
        "--texas",
        "--utah",
        "--virginia",
        "--vermont",
        "--washington",
        "--wisconsin",
        "--west-virginia",
        "--wyoming",
        "without state status"
    ],
    "soil_adp_m_txt_ind": [
        "yes",
        "no"
    ],
    "bloat_pot_condition": [
        "none",
        "low",
        "medium",
        "high"
    ],
    "palatable_human_ind": [
        "yes",
        "no"
    ],
    "prpg_ctnr_ind": [
        "yes",
        "no"
    ],
    "growth_habit_condition": [
        "bunch",
        "colonizing",
        "multiple stem",
        "rhizomatous",
        "single crown",
        "single stem",
        "stoloniferous",
        "thicket forming"
    ],
    "fire_tolerance_condition": [
        "none",
        "low",
        "medium",
        "high"
    ],
    "navl_stor_suit_ind": [
        "yes",
        "no"
    ],
    "grwhabt": [
        "forb/herb",
        "graminoid",
        "lichenous",
        "nonvascular",
        "shrub",
        "subshrub",
        "tree",
        "vine"
    ],
    "moist_use_condition": [
        "low",
        "medium",
        "high"
    ],
    "anerb_tolerance_condition": [
        "none",
        "low",
        "medium",
        "high"
    ],
    "family": [
        "acanthaceae",
        "acarosporaceae",
        "aceraceae",
        "achatocarpaceae",
        "acoraceae",
        "acrobolbaceae",
        "actinidiaceae",
        "adelococcaceae",
        "adoxaceae",
        "agavaceae",
        "agyriaceae",
        "aizoaceae",
        "alectoriaceae",
        "alismataceae",
        "allisoniaceae",
        "aloaceae",
        "amaranthaceae",
        "amblystegiaceae",
        "anacardiaceae",
        "andreaeaceae",
        "andreaeobryaceae",
        "anemiaceae",
        "aneuraceae",
        "annonaceae",
        "anomodontaceae",
        "antheliaceae",
        "anthocerotaceae",
        "apiaceae",
        "apocynaceae",
        "aponogetonaceae",
        "aquifoliaceae",
        "araceae",
        "araliaceae",
        "araucariaceae",
        "archidiaceae",
        "arctomiaceae",
        "arecaceae",
        "aristolochiaceae",
        "arnelliaceae",
        "arthoniaceae",
        "arthopyreniaceae",
        "arthrorhaphidaceae",
        "asclepiadaceae",
        "aspleniaceae",
        "asteraceae",
        "asterothyriaceae",
        "atheliaceae",
        "aulacomniaceae",
        "aytoniaceae",
        "azollaceae",
        "bacidiaceae",
        "baeomycetaceae",
        "balanophoraceae",
        "balsaminaceae",
        "bartramiaceae",
        "basellaceae",
        "bataceae",
        "begoniaceae",
        "berberidaceae",
        "betulaceae",
        "biatorellaceae",
        "bignoniaceae",
        "bixaceae",
        "blasiaceae",
        "blechnaceae",
        "bombacaceae",
        "boraginaceae",
        "brachytheciaceae",
        "brassicaceae",
        "brigantiaceae",
        "bromeliaceae",
        "bruchiaceae",
        "brunelliaceae",
        "bryaceae",
        "bryoxiphiaceae",
        "buddlejaceae",
        "burmanniaceae",
        "burseraceae",
        "butomaceae",
        "buxaceae",
        "buxbaumiaceae",
        "cabombaceae",
        "cactaceae",
        "caliciaceae",
        "callicostaceae",
        "callitrichaceae",
        "calycanthaceae",
        "calyceraceae",
        "calymperaceae",
        "calypogeiaceae",
        "campanulaceae",
        "candelariaceae",
        "canellaceae",
        "cannabaceae",
        "cannaceae",
        "capnodiaceae",
        "capparaceae",
        "caprifoliaceae",
        "caricaceae",
        "caryocaraceae",
        "caryophyllaceae",
        "casuarinaceae",
        "catillariaceae",
        "catoscopiaceae",
        "caulerpaceae",
        "cecropiaceae",
        "celastraceae",
        "cephalotaxaceae",
        "cephaloziaceae",
        "cephaloziellaceae",
        "ceratophyllaceae",
        "cercidiphyllaceae",
        "chenopodiaceae",
        "chionosphaeraceae",
        "chloranthaceae",
        "chonecoleaceae",
        "chrysobalanaceae",
        "chrysotrichaceae",
        "cistaceae",
        "cladoniaceae",
        "clavariaceae",
        "clethraceae",
        "cleveaceae",
        "climaciaceae",
        "clusiaceae",
        "coccocarpiaceae",
        "coccotremataceae",
        "collemataceae",
        "combretaceae",
        "commelinaceae",
        "coniocybaceae",
        "connaraceae",
        "conocephalaceae",
        "convolvulaceae",
        "cornaceae",
        "corsiniaceae",
        "corticiaceae",
        "corynocarpaceae",
        "costaceae",
        "crassulaceae",
        "crocyniaceae",
        "crossosomataceae",
        "cryphaeaceae",
        "cucurbitaceae",
        "cunoniaceae",
        "cupressaceae",
        "cuscutaceae",
        "cyatheaceae",
        "cycadaceae",
        "cyclanthaceae",
        "cymodoceaceae",
        "cyperaceae",
        "cyrillaceae",
        "dacampiaceae",
        "dactylosporaceae",
        "daltoniaceae",
        "datiscaceae",
        "davalliaceae",
        "dendrocerotaceae",
        "dennstaedtiaceae",
        "diapensiaceae",
        "dicksoniaceae",
        "dicranaceae",
        "dilleniaceae",
        "dioscoreaceae",
        "dipsacaceae",
        "dipterocarpaceae",
        "disceliaceae",
        "ditrichaceae",
        "droseraceae",
        "dryopteridaceae",
        "ebenaceae",
        "ectolechiaceae",
        "eigleraceae",
        "elaeagnaceae",
        "elaeocarpaceae",
        "elatinaceae",
        "empetraceae",
        "encalyptaceae",
        "entodontaceae",
        "epacridaceae",
        "ephedraceae",
        "ephemeraceae",
        "equisetaceae",
        "eremolepidaceae",
        "ericaceae",
        "eriocaulaceae",
        "erpodiaceae",
        "erythroxylaceae",
        "euphorbiaceae",
        "fabaceae",
        "fabroniaceae",
        "fagaceae",
        "fissidentaceae",
        "flacourtiaceae",
        "flagellariaceae",
        "fontinalaceae",
        "fossombroniaceae",
        "fouquieriaceae",
        "frankeniaceae",
        "fumariaceae",
        "funariaceae",
        "fuscideaceae",
        "garryaceae",
        "gentianaceae",
        "geocalycaceae",
        "geraniaceae",
        "gesneriaceae",
        "gigaspermaceae",
        "ginkgoaceae",
        "gleicheniaceae",
        "gnetaceae",
        "gomphillaceae",
        "goodeniaceae",
        "gracilariaceae",
        "grammitidaceae",
        "graphidaceae",
        "greyiaceae",
        "grimmiaceae",
        "grossulariaceae",
        "gunneraceae",
        "gyalectaceae",
        "gymnomitriaceae",
        "gypsoplaceae",
        "gyrothyraceae",
        "haematommataceae",
        "haemodoraceae",
        "haloragaceae",
        "halymeniaceae",
        "hamamelidaceae",
        "hanguanaceae",
        "haplomitriaceae",
        "hedwigiaceae",
        "heliconiaceae",
        "helodiaceae",
        "heppiaceae",
        "herbertaceae",
        "hernandiaceae",
        "hippocastanaceae",
        "hippocrateaceae",
        "hippuridaceae",
        "hookeriaceae",
        "hydrangeaceae",
        "hydrocharitaceae",
        "hydrophyllaceae",
        "hylocomiaceae",
        "hymeneliaceae",
        "hymenophyllaceae",
        "hypnaceae",
        "hypocreaceae",
        "hypopterygiaceae",
        "icacinaceae",
        "illiciaceae",
        "iridaceae",
        "isoetaceae",
        "joinvilleaceae",
        "jubulaceae",
        "juglandaceae",
        "juncaceae",
        "juncaginaceae",
        "jungermanniaceae",
        "krameriaceae",
        "lamiaceae",
        "lardizabalaceae",
        "lauraceae",
        "lecanoraceae",
        "lecideaceae",
        "lecythidaceae",
        "leitneriaceae",
        "lejeuneaceae",
        "lemnaceae",
        "lennoaceae",
        "lentibulariaceae",
        "leotiaceae",
        "lepidoziaceae",
        "leptodontaceae",
        "leskeaceae",
        "letrouitiaceae",
        "leucobryaceae",
        "leucodontaceae",
        "lichenotheliaceae",
        "lichinaceae",
        "liliaceae",
        "limnanthaceae",
        "limnocharitaceae",
        "linaceae",
        "loasaceae",
        "lobariaceae",
        "loganiaceae",
        "lophosoriaceae",
        "loranthaceae",
        "lunulariaceae",
        "lycopodiaceae",
        "lygodiaceae",
        "lythraceae",
        "magnoliaceae",
        "malpighiaceae",
        "malvaceae",
        "marantaceae",
        "marattiaceae",
        "marcgraviaceae",
        "marchantiaceae",
        "marsileaceae",
        "mastigophoraceae",
        "mastodiaceae",
        "mayacaceae",
        "meesiaceae",
        "megalosporaceae",
        "melanommataceae",
        "melaspileaceae",
        "melastomataceae",
        "meliaceae",
        "melianthaceae",
        "menispermaceae",
        "menyanthaceae",
        "mesoptychiaceae",
        "meteoriaceae",
        "metzgeriaceae",
        "micareaceae",
        "microcaliciaceae",
        "mniaceae",
        "molluginaceae",
        "monimiaceae",
        "monoblastiaceae",
        "monosoleniaceae",
        "monotropaceae",
        "moraceae",
        "moringaceae",
        "musaceae",
        "mycoblastaceae",
        "mycocaliciaceae",
        "mycoporaceae",
        "mycosphaerellaceae",
        "myoporaceae",
        "myricaceae",
        "myriniaceae",
        "myristicaceae",
        "myrsinaceae",
        "myrtaceae",
        "myxotrichaceae",
        "najadaceae",
        "neckeraceae",
        "nelumbonaceae",
        "nepenthaceae",
        "nephromataceae",
        "notothyladaceae",
        "nyctaginaceae",
        "nymphaeaceae",
        "ochnaceae",
        "odontotremataceae",
        "oedipodiaceae",
        "olacaceae",
        "oleaceae",
        "onagraceae",
        "opegraphaceae",
        "ophioglossaceae",
        "ophioparmaceae",
        "orchidaceae",
        "orobanchaceae",
        "orthotrichaceae",
        "osmundaceae",
        "oxalidaceae",
        "oxymitraceae",
        "paeoniaceae",
        "pallaviciniaceae",
        "pandanaceae",
        "pannariaceae",
        "papaveraceae",
        "parkeriaceae",
        "parmeliaceae",
        "passifloraceae",
        "pedaliaceae",
        "pelliaceae",
        "peltigeraceae",
        "peltulaceae",
        "pertusariaceae",
        "philydraceae",
        "phlyctidaceae",
        "phyllachoraceae",
        "physciaceae",
        "phytolaccaceae",
        "pilocarpaceae",
        "pinaceae",
        "piperaceae",
        "pittosporaceae",
        "placynthiaceae",
        "plagiochilaceae",
        "plagiotheciaceae",
        "plantaginaceae",
        "platanaceae",
        "platygloeaceae",
        "pleomassariaceae",
        "pleosporaceae",
        "pleuroziaceae",
        "pleuroziopsidaceae",
        "plumbaginaceae",
        "poaceae",
        "podocarpaceae",
        "podostemaceae",
        "polemoniaceae",
        "polygalaceae",
        "polygonaceae",
        "polypodiaceae",
        "polytrichaceae",
        "pontederiaceae",
        "porellaceae",
        "porpidiaceae",
        "portulacaceae",
        "posidoniaceae",
        "potamogetonaceae",
        "pottiaceae",
        "primulaceae",
        "proteaceae",
        "protothelenellaceae",
        "pseudoditrichaceae",
        "pseudolepicoleaceae",
        "psilotaceae",
        "psoraceae",
        "pteridaceae",
        "pterigynandraceae",
        "pterobryaceae",
        "ptilidiaceae",
        "ptychomitriaceae",
        "punicaceae",
        "pyrenotrichaceae",
        "pyrenulaceae",
        "pyrolaceae",
        "racopilaceae",
        "radulaceae",
        "rafflesiaceae",
        "ramalinaceae",
        "ranunculaceae",
        "resedaceae",
        "rhachitheciaceae",
        "rhamnaceae",
        "rhizocarpaceae",
        "rhizogoniaceae",
        "rhizophoraceae",
        "rhytidiaceae",
        "ricciaceae",
        "riellaceae",
        "rimulariaceae",
        "roccellaceae",
        "rosaceae",
        "rubiaceae",
        "ruppiaceae",
        "rutaceae",
        "sabiaceae",
        "salicaceae",
        "salviniaceae",
        "santalaceae",
        "sapindaceae",
        "sapotaceae",
        "sarraceniaceae",
        "saururaceae",
        "saxifragaceae",
        "scapaniaceae",
        "schaereriaceae",
        "scheuchzeriaceae",
        "schisandraceae",
        "schistostegaceae",
        "schizaeaceae",
        "scouleriaceae",
        "scrophulariaceae",
        "selaginellaceae",
        "seligeriaceae",
        "sematophyllaceae",
        "simaroubaceae",
        "simmondsiaceae",
        "smilacaceae",
        "solanaceae",
        "solorinellaceae",
        "sonneratiaceae",
        "sparganiaceae",
        "sphaerocarpaceae",
        "sphaerophoraceae",
        "sphagnaceae",
        "sphenocleaceae",
        "sphinctrinaceae",
        "splachnaceae",
        "splachnobryaceae",
        "stackhousiaceae",
        "staphyleaceae",
        "stemonaceae",
        "sterculiaceae",
        "stereocaulaceae",
        "stereophyllaceae",
        "stictidaceae",
        "strelitziaceae",
        "strigulaceae",
        "styracaceae",
        "surianaceae",
        "symplocaceae",
        "syzygosporaceae",
        "taccaceae",
        "tamaricaceae",
        "targioniaceae",
        "taxaceae",
        "teloschistaceae",
        "tetraphidaceae",
        "thamnobryaceae",
        "theaceae",
        "thelenellaceae",
        "theliaceae",
        "thelotremataceae",
        "thelypteridaceae",
        "theophrastaceae",
        "thrombiaceae",
        "thuidiaceae",
        "thymelaeaceae",
        "tiliaceae",
        "timmiaceae",
        "trapaceae",
        "trapeliaceae",
        "tremellaceae",
        "treubiaceae",
        "trichocoleaceae",
        "trichocomaceae",
        "tricholomataceae",
        "trichotheliaceae",
        "triuridaceae",
        "tropaeolaceae",
        "trypetheliaceae",
        "turneraceae",
        "typhaceae",
        "ulmaceae",
        "ulvaceae",
        "umbilicariaceae",
        "urticaceae",
        "valerianaceae",
        "verbenaceae",
        "verrucariaceae",
        "vezdaeaceae",
        "violaceae",
        "viscaceae",
        "vitaceae",
        "vittariaceae",
        "winteraceae",
        "xyridaceae",
        "zamiaceae",
        "zannichelliaceae",
        "zingiberaceae",
        "zosteraceae",
        "zygophyllaceae"
    ],
    "hybrids": [
        "only hybrids",
        "only non-hybrids"
    ],
    "folg_txt_condition": [
        "fine",
        "medium",
        "coarse"
    ],
    "nreg_wet_status": [
        "with wetland status",
        "--obl (obligate wetland)",
        "--obl* (tentatively obligate wetland)",
        "--facw+ (facultative wetland+)",
        "--facw (facultative wetland)",
        "--facw* (tentatively facultative wetland)",
        "--facw- (facultative wetland-)",
        "--facw-* (tentatively facultative wetland-)",
        "--fac+ (facultative+)",
        "--fac+* (tentatively facultative+)",
        "--fac (facultative)",
        "--fac* (tentatively facultative)",
        "--fac- (facultative-)",
        "--fac-* (tentatively facultative-)",
        "--facu+ (facultative upland+)",
        "--facu+* (tentatively facultative upland+)",
        "--facu (facultative upland)",
        "--facu* (tentatively facultative upland)",
        "--facu- (facultative upland-)",
        "--facu-* (tentatively facultative upland-)",
        "--upl (obligate upland)",
        "--upl* (tentatively obligate upland)",
        "without wetland status (upland plants)"
    ],
    "leaf_retnt_ind": [
        "yes",
        "no"
    ],
    "fed_te_status": [
        "with federal status",
        "--endangered",
        "--threatened",
        "without federal status"
    ],
    "soil_adp_f_txt_ind": [
        "yes",
        "no"
    ],
    "wet_region": [
        "region 1 (northeast)",
        "region 2 (southeast)",
        "region 3 (north central)",
        "region 4 (north plains)",
        "region 5 (central plains)",
        "region 6 (south plains)",
        "region 7 (southwest)",
        "region 8 (intermountain)",
        "region 9 (northwest)",
        "region 0 (california)",
        "region a (alaska)",
        "region c (caribbean)",
        "region h (hawaii)"
    ],
    "prpg_tubr_ind": [
        "yes",
        "no"
    ],
    "plantfact_ind": [
        "only with fact sheets",
        "only without fact sheets"
    ],
    "grass_low_grw_ind": [
        "yes",
        "no"
    ],
    "pfa": [
        "plants floristic area",
        "--north america",
        "\u00a0\u00a0--lower 48 u.s. states",
        "\u00a0\u00a0--alaska",
        "\u00a0\u00a0--canada",
        "\u00a0\u00a0--greenland (denmark)",
        "\u00a0\u00a0--st. pierre and miquelon (france)",
        "--hawaii",
        "--puerto rico",
        "--virgin islands",
        "not in plants floristic area"
    ],
    "coppice_pot_ind": [
        "yes",
        "no"
    ],
    "fed_nox_status_ind": [
        "with federal status",
        "--noxious weed",
        "--quarantine",
        "without federal status"
    ],
    "sm_grain_ind": [
        "yes",
        "no"
    ],
    "statefips": [
        "u.s. states",
        "--alabama",
        "--alaska",
        "--arizona",
        "--arkansas",
        "--california",
        "--colorado",
        "--connecticut",
        "--delaware",
        "--district of columbia",
        "--florida",
        "--georgia",
        "--hawaii",
        "--idaho",
        "--illinois",
        "--indiana",
        "--iowa",
        "--kansas",
        "--kentucky",
        "--louisiana",
        "--maine",
        "--maryland",
        "--massachusetts",
        "--michigan",
        "--minnesota",
        "--mississippi",
        "--missouri",
        "--montana",
        "--nebraska",
        "--nevada",
        "--new hampshire",
        "--new jersey",
        "--new mexico",
        "--new york",
        "--north carolina",
        "--north dakota",
        "--ohio",
        "--oklahoma",
        "--oregon",
        "--pennsylvania",
        "--rhode island",
        "--south carolina",
        "--south-dakota",
        "--tennessee",
        "--texas",
        "--utah",
        "--vermont",
        "--virginia",
        "--washington",
        "--west-virginia",
        "--wisconsin",
        "--wyoming",
        "u.s. territories and protectorates",
        "--puerto rico",
        "--virgin islands",
        "canada",
        "--alberta",
        "--british columbia",
        "--manitoba",
        "--new brunswick",
        "--newfoundland and labrador",
        "\u00a0\u00a0--labrador",
        "\u00a0\u00a0--newfoundland",
        "--northwest territories",
        "--nova scotia",
        "--nunavut",
        "--ontario",
        "--prince edward island",
        "--qu\u00e9bec",
        "--saskatchewan",
        "--yukon",
        "denmark",
        "--greenland",
        "france",
        "--st. pierre and miquelon"
    ],
    "image_ind": [
        "only with images",
        "-- only with photos",
        "-- only with drawings",
        "only without images"
    ],
    "alepth_ind": [
        "yes",
        "no"
    ],
    "plnt_den_low_range": [
        "10-299",
        "300-549",
        "550-799",
        "800-1299",
        "1300-1799",
        "1800-2999",
        "3000-3999",
        "4000-4999",
        "5000-12999",
        "13000-22999",
        "23000-32999",
        "33000-44000"
    ],
    "n_fix_pot_condition": [
        "none",
        "low",
        "medium",
        "high"
    ],
    "plnt_den_high_range": [
        "50-499",
        "500-999",
        "1000-1499",
        "1500-2499",
        "2500-3499",
        "3500-4499",
        "4500-5499",
        "5500-10499",
        "10500-18999",
        "19000-71999",
        "72000-125000"
    ],
    "frut_seed_color_condition": [
        "black",
        "blue",
        "brown",
        "green",
        "orange",
        "purple",
        "red",
        "white",
        "yellow"
    ],
    "seed_sprd_rate_condition": [
        "none",
        "slow",
        "moderate",
        "rapid"
    ],
    "frut_seed_cspc_ind": [
        "yes",
        "no"
    ],
    "fall_cspc_ind": [
        "yes",
        "no"
    ],
    "frut_seed_end_condition": [
        "spring",
        "summer",
        "fall",
        "winter",
        "year-round"
    ],
    "invasive_pubs": [
        "with invasive status",
        "--cal-ipc-exotic pest plant list",
        "--fleppc-invasive plant list",
        "--hear-information index for selected alien plants in hawaii",
        "--ky-weeds of kentucky and adjacent states: a field guide",
        "--n'east-weeds of the northeast",
        "--ne&gp-weeds of nebraska and the great plains",
        "--seeppc-invasive exotic pest plants in tennessee",
        "--state-state noxious weed lists for 35 states",
        "--swss-weeds of the united states and canada",
        "--us-federal noxious weed list",
        "--wi-wisconsin manual of control recommendations for ecologically invasive plants",
        "--wsws-weeds of the west",
        "without invasive status"
    ],
    "plantchar_ind": [
        "only with characteristics data",
        "only without characteristics data"
    ],
    "caco3_tolerance_condition": [
        "none",
        "low",
        "medium",
        "high"
    ],
    "soil_ph_tolerance_min_range": [
        "3.5-3.6",
        "3.7-3.8",
        "3.9-4",
        "4.1-4.2",
        "4.3-4.4",
        "4.5-4.6",
        "4.7-4.8",
        "4.9-5",
        "5.1-5.2",
        "5.3-5.4",
        "5.5-5.6",
        "5.7-5.8",
        "5.9-6",
        "6.1-6.2",
        "6.3-6.4",
        "6.5-6.6",
        "6.7-6.8",
        "6.9-7",
        "7.1-7.2",
        "7.3-7.4",
        "7.5-7.6",
        "7.7-7.8",
        "7.9-8",
        "8.1-8.2",
        "8.3-8.4",
        "8.5-8.6",
        "8.7-8.8",
        "8.9-9",
        "9.1-9.2",
        "9.3-9.4",
        "9.5-9.6",
        "9.7-9.8",
        "9.9-10",
        "10.1"
    ],
    "height_max_base_age_range": [
        "1-1.9",
        "2-2.9",
        "3-3.9",
        "4-5.9",
        "6-9.9",
        "10-14.9",
        "15-19.9",
        "20-24.9",
        "25-29.9",
        "30-39.9",
        "40-59.9",
        "60-79.9",
        "80-130"
    ],
    "frut_body_suit_ind": [
        "yes",
        "no"
    ],
    "rsprt_able_ind": [
        "yes",
        "no"
    ],
    "palat_animl_grz_condition": [
        "low",
        "medium",
        "high"
    ],
    "growth_prd_actv_condition": [
        "spring",
        "spring and fall",
        "spring and summer",
        "spring, summer, fall",
        "summer",
        "summer and fall",
        "fall, winter and spring",
        "year-round"
    ],
    "prpg_cut_ind": [
        "yes",
        "no"
    ],
    "folg_prsty_wntr_condition": [
        "porous",
        "moderate",
        "dense"
    ],
    "folg_prsty_sumr_condition": [
        "porous",
        "moderate",
        "dense"
    ],
    "frut_seed_start_condition": [
        "spring",
        "summer",
        "fall",
        "winter",
        "year-round"
    ],
}

SEED_PER_LB_Range = [
    "10-99999",
    "100000-199999",
    "200000-299999",
    "300000-399999",
    "400000-499999",
    "500000-999999",
    "1000000-1499999",
    "1500000-9999999",
    "10000000-19999999",
    "20000000-29999999",
    "30000000-39999999",
    "40000000-49999999"
]

PROPAGATION_METHODS = [
    {"type": "corm", "recommended_months": []},
    {
        "type": "sprigs", "recommended_months": []
    },
    {
        "type": "tubers", "recommended_months": []
    },
    {
        "type": "bulb", "recommended_months": []
    },
    {
        "type": "seed",
        "success_factors": [
            {
                "name": "scarification", "value": True,
                "recommended_months": ["april", "may"]
            },
            {
                "name": "stratification", "value": True,
                "recommended_months": ["april", "may"]
            },
        ]
    },
    {
        "type": "sod", "recommended_months": []
    },
    {
        "type": "tissue_culture", "recommended_months": []
    },
    {
        "type": "vegetative_cutting_semiripe",
        "success_factors": [
            {"name": "IBA", "value": "1000", "units": "PPM"},
            {"name": "NAA", "value": "1000", "units": "PPM"},
            {"name": "IAA", "value": "1000", "units": "PPM"},
        ],
        "recommended_months": []
    },
    {
        "type": "vegetative_cutting_greenwood", "recommended_months": []
    },
    {
        "type": "vegetative_cutting_hardwood", "recommended_months": []
    },
    {
        "type": "vegetative_cutting_softwood", "recommended_months": []
    },
    {
        "type": "bare_root", "recommended_months": []
    },
    {
        "type": "root_division",
        "recommended_months": ["october", "november", "december"]
    }
]

GROWTH_REQUIREMENTS = {
    "aspect_hours": 6.0,
    "aspect": "sun/half-shade",
    "moisture_use": "medium",
    "ph": {
        "type": "str",
        "anyof": SOIL_PH_TOLERANCE_MAX_RANGE
    },
    "planting_density_per_acre": None,

    "precipitation": {
        "min": {
            "type": "string", "anyof": PRECIPATION_TOLERANCE_MAX_RANGE,
        },
        "max": {
            "type": "string", "anyof": PRECIPATION_TOLERANCE_MIN_RANGE,
        }
    },
    "temperature": {
        "min": -40,
        "max": 90
    },
    "tolerance": {
        "fire": "high",
        "salinity": "intermediate",
        "shade": {
            "type": "string",
            "anyof": [
                "intolerant",
                "intermediate",
                "tolerant"
            ]
        },
        "drought": "low",
        "frost_free_days_min": {
            "type": "string",
            "anyof": [
                "0-51",
                "52-66",
                "67-81",
                "82-96",
                "97-111",
                "112-126",
                "127-141",
                "142-156",
                "157-171",
                "172-186",
                "187-201",
                "202-216",
                "217-231",
                "232-246",
                "247-261",
                "262-276",
                "277-291",
                "292-306",
                "307-321",
                "322-336",
                "337-351",
                "352-365"
            ],
        },
        "hedge": {
            "type": "string",
            "anyof": [
                "none",
                "low",
                "medium",
                "high",
            ],
        },
    },
    "soil": {
        "preferred_type": "sandy-loam",
        "adaptations": {
            "coarse_texture": False,
            "medium_texture": False,
            "fine_texture": True,
            "anaerobic_tolerance": None,
            "calcareous_tolerance": None,
        }
    },
    "water_requirements": "mostly_wet",
    "drainage": "well-drained",
    "hardiness": {
        "usda_zone": {
            "type": "string",
            "anyof": [
                "1a", "1b",
                "2a", "2b",
                "3a", "3b",
                "4a", "4b",
                "5a", "5b",
                "6a", "6b",
                "7a", "7b",
                "8a", "8b",
                "9a", "9b",
                "10a", "10b",
                "11a", "11b",
                "12a", "12b",
                "13a", "13b",
            ]
        },
        "sunset_zone": [],
    },
    "root": {
        "depth": {
            "type": "string",
            "anyof": ROOT_DEPTH_MIN_RANGE,
        },
        "primary_type": "taproot",
    }
}

TAXONOMY = {
    "cultivars": [
        {
            "name": "string",
            "flower_colors": ["string"],
            "description": "string",
        },
    ],
    "category": {
        "type": "string",
        "anyof": taxonomy.PLANT_CATEGORY,
    },
    "scientific_name": "acaena caesiiglauca",
    "family": {
        "name": "rosaceae",
        "common_name": {
            "type": "string",
            "anyof": taxonomy.PLANT_COMMON_FAMILY_NAMES,
        },
        "symbol": None,
    },
    "genus": {
        "type": "string",
        "anyof": taxonomy.PLANT_GENUSES,
    },
    "order": {
        "type": "string",
        "anyof": taxonomy.PLANT_ORDERS,
    },
    "subclass": {
        "type": "string",
        "anyof": taxonomy.PLANT_SUBCLASSES,
    },
    "class": {
        "type": "string",
        "anyof": taxonomy.PLANT_CLASSES,
    },
    "subdivision": {
        "type": "string",
        "anyof": taxonomy.PLANT_SUBDIVISIONS,
    },
    "division": {
        "type": "string",
        "anyof": taxonomy.PLANT_DIVISIONS,
    },
    "superdivision": {
        "type": "string",
        "anyof": taxonomy.PLANT_SUPERDIVISIONS,
    },
    "subkingdom": {
        "type": "string",
        "anyof": taxonomy.PLANT_SUBKINGDOMS,
    },
    "kingdom": {
        "type": "string",
        "anyof": taxonomy.PLANT_KINGDOMS,
    },
    "itis_tns": None,
    "national_common_name": "sheepburr",
    "common_aliases": []
}
LEGAL = {
    "copyrighted": False,
    "gmo": False,
    "patented": False,
    "us_federal_noxious_status": None,
    "us_federal_noxious_common_name": None,
    "us_state_noxious_status": None,
    "us_plant_invasive_status": None,
    "us_federal_te_status": None,
    "us_federal_te_common_name": None,
    "us_state_te_status": None,
    "us_state_te_common_name": None,
    "us_national_wetland_indicator_status": None,
    "us_regional_wetland_indicator_region": None,
    "us_regional_wetland_indicator_status": None
}

REPRODUCTION = {
    "fertility_requirement": "low",
    "sexual_organs": {
        "type": "string",
        "nullable": True,
        "anyof": [
            "hermaphroditic",
            "unisexual"
        ],
    },
    "unisex_type": {
        "nullable": True,
        "type": "string",
        "anyof": [
            "monoecious",
            "dioecious",
        ],
    },
    "stamens": None,
    "pistil": None,
    "pollination": {
        # https://en.wikipedia.org/wiki/Flower#Attraction_methods
        "attraction_method": "nectar",
        "attraction_speciality": "ultraviolet",
        "mechanism": [
            "entomophilous",
            "anemophilous",
        ],
        "methods": {
            "abiotic": {
                "nullable": True,
                "type": "string",
                "anyof": [
                    "wind (anemophily)",
                    "water (hydrophily)"
                ],
            },
            "biotic": {
                "nullable": True,
                "type": "string",
                "anyof": [
                    "insects (entomophily)",
                    "birds (ornithophily)",
                    "bats (chiropterophily)"
                ],
            },
        },
    },
    "bloom_period": {
        "type": "string",
        "anyof": [
            "spring",
            "early spring",
            "mid spring",
            "late spring",
            "summer",
            "early summer",
            "mid summer",
            "late summer",
            "fall",
            "winter",
            "late winter",
            "indeterminate"
        ],
    },
    "commercial_availability": None,
    "fruit_seed": {
        "dispersal": {
            # https://en.wikipedia.org/wiki/Biological_dispersal#Types_of_dispersal
            "type": {
                "nullable": True,
                "type": "string",
                "anyof": [
                    "density-independent",
                    "density-dependent",
                    "breeding",
                    "natal",
                ],
            },
            "shape": None,
            "spread_rate": "slow",
            "range": None,
            "per_pound": {
                "type": "string",
                "anyof": SEED_PER_LB_Range,
            },
        },
        "seedling_vigor": {
            "type": "string",
            "anyof": [
                "low",
                "medium",
                "high",
            ],
        },
        "small_grain": True,
        "color": None,
        "conspicous": None,
        "abundance": "low",
        "period": {
            "begin": "spring",
            "end": "fall",
            "persistence": True
        }
    }
}

SCHEMA = {
    "taxonomy": TAXONOMY,
    "ecology": {
        "duration": {
            "type": "string",
            "anyof": [
                "annual",
                "biennial",
                "perennial",
                "unknown"
            ]
        },
        "growth_habitat": "forb",
        "native_status": None
    },
    "distribution": {
        "locales": {
            "type": "string",
            # TODO: add world countries, etc... granularity TBD.
            "anyof": locales.US_COUNTIES
        },
        "endemic": False
    },
    "hardwood": False,
    "hardwood_scale": None,
    "propagation_methods": PROPAGATION_METHODS,
    "tags": {
        "type": "list",
        "schema": {
            "type": "string",
        },
    },
    "legal": LEGAL,
    "morphology_and_physiology": {
        # http://www.backyardnature.net/treebark.htm
        "bark": {
            "type": "list",
            "schema": {
                "type": "string",
                "anyof": [
                    "smooth",
                    "scaly",
                    "plated",
                    "warty",
                    "shaggy",
                    "papery",
                    "furrowed",
                    "fibrous"
                ],
            },
            "thickness": None,
            "color": None
        },
        "active_growth_period": None,
        "after_harvest_regrowth_rate": None,
        "bloat": None,
        "c_to_n_ratio": {
            "type": "string",
            "anyof": [
                "low",
                "medium",
                "high"
            ]
        },
        "coppice_potential": None,
        "fall_conspicous": None,
        "fire_resistance": {"type": "bool"},
        "flower": {
            "flower_type": "rosate",
            "inflorescence": True,
            "color": None,
            "conspicous": None,
            # https://en.wikipedia.org/wiki/Floral_formula
            "floral_formula": "↯ K3 [C3 A1°–3°+½:2°] Ğ(3)"
        },
        "foliage": {
            "type": {
                "type": "string",
                "anyof": foliage.FOLIAGE_TYPES,
            },
            "anatomy": {
                "type": "string",
                "anyof": foliage.FOLIAGE_MORPHOLOGY_TYPES
            },
            "arrangement": {
                "type": "string",
                "anyof": foliage.FOLIAGE_ARRANGEMENT_TYPES,
            },
            "foliage_color": "green",
            "porosity_summer": None,
            "porosity_winter": None,
            "texture": None,
            "striped": False,
            "variegated": False
        },
        "growth": {
            "form": {
                "type": "string",
                "anyof": GROWTH_FORMS,
            },
            "vegetate_spread_rate": {
                "type": "string",
                "anyof": [
                    "slow",
                    "moderate",
                    "rapid"
                ],
            },
            "avg_root_depth": "2ft",
            "avg_spread": "3ft",
            "avg_landscape_size": "Fast grower to 24 to 36 in.",
            "avg_per_year": "2ft",
        },
        "height": {
            "avg": "5in",
            "at_base_max": 0.0,
            "at_maturity_range": {
                "type": "string",
                "anyof": [
                    "0-0.9",
                    "1-1.9",
                    "2-2.9",
                    "3-3.9",
                    "4-5.9",
                    "6-9.9",
                    "10-19.9",
                    "20-39.9",
                    "40-59.9",
                    "60-99.9",
                    "100-149.9",
                    "150-199.9",
                    "200-250"
                ],
            },
        },
        "leaf_retention": True,
        "lifespan": "moderate",
        "low_growing_grass": None,
        "nitrogen_fixation": None,
        "resprout_ability": None,
        "shape_and_orientation": None,
    },
    "concerns": {
        "allelopathic": False,
        "toxicity": {
            "type": "str",
            "anyof": [
                "none",
                "slight",
                "moderate",
                "severe",
            ],
        },
        "toxicity_locations": {
            "type": "list",
            "anyof": [
                "root", "leaf", "stem",
            ]
        },
    },
    "reproduction": REPRODUCTION,
    "growth_requirements": GROWTH_REQUIREMENTS,
    # https://plants.usda.gov/adv_search.html
    # "Suitability/Use" section.
    "suitability_use": {
        "berry_nut_seed": None,
        "christmas_tree": {
            "type": "bool",
            "default": False,
        },
        "fodder": None,
        "fuelwood": {
            "type": "string",
            "anyof": [
                "low",
                "medium",
                "high",
            ],
        },
        "lumber": {
            "type": "bool",
            "default": False,
        },
        "naval_store_product": {
            "type": "bool",
            "default": False,
        },
        "nursery_stock_product": {
            "type": "bool",
            "default": True,
        },
        "palatable_browse_animal": None,
        "post_product": None,
        "protein_potential_condition": {
            "type": "string",
            "anyof": [
                "low",
                "medium",
                "high"
            ],
        },
        "pulpwood_product": {"type": "bool"},
        "veneer_product": None,
        "carbon_sequestration": {
            "type": "string",
            "anyof": ["low", "medium", "high"],
        },
    },
}
