"""Taxonomy, naming categories."""

PLANT_CATEGORY = [
    "dicot",
    "fern",
    "green alga",
    "gymnosperm",
    "hornwort",
    "horsetail",
    "lichen",
    "liverwort",
    "lycopod",
    "monocot",
    "moss",
    "quillwort",
    "red algae",
    "whisk-fern"
]
PLANT_GENUSES = []
PLANT_SUBCLASSES = [
    "alismatidae",
    "andreaeidae",
    "arecidae",
    "bryidae",
    "caryophyllidae",
    "commelinidae",
    "dilleniidae",
    "hamamelididae",
    "jungermanniae",
    "liliidae",
    "magnoliidae",
    "marchantiae",
    "rosidae",
    "sphagnidae",
    "zingiberidae",
]
PLANT_CLASSES = [
    "andreaeopsida",
    "anthocerotopsida",
    "ascomycetes",
    "basidiomycetes",
    "bryopsida",
    "chlorophyceae",
    "cycadopsida",
    "equisetopsida",
    "filicopsida",
    "florideophyceae",
    "ginkgoopsida",
    "gnetopsida",
    "hepaticopsida",
    "liliopsida",
    "lycopodiopsida",
    "magnoliopsida",
    "pinopsida",
    "psilopsida",
    "sphagnopsida",
    "ulvophyceae",
    "ustomycetes"
]
PLANT_SUPERDIVISIONS = [
    "spermatophyta"
]
PLANT_SUBDIVISIONS = [
    "anthocerotae",
    "hepaticae",
    "musci"
]
PLANT_SUBKINGDOMS = ["tracheobionta"]
PLANT_KINGDOMS = [
    "plantae",
    "fungi"
]
PLANT_DIVISIONS = [
    "anthocerotophyta",
    "ascomycota",
    "basidiomycota",
    "bryophyta",
    "chlorophyta",
    "coniferophyta",
    "cycadophyta",
    "equisetophyta",
    "ginkgophyta",
    "gnetophyta",
    "hepaticophyta",
    "lycopodiophyta",
    "magnoliophyta",
    "mitosporic fungi",
    "psilophyta",
    "pteridophyta",
    "rhodophyta"
]
PLANT_ORDERS = [
    "agaricales",
    "alismatales",
    "andreaeales",
    "andreaeobryales",
    "anthocerotales",
    "apiales",
    "arales",
    "archidiales",
    "arecales",
    "aristolochiales",
    "arthoniales",
    "asterales",
    "atractiellales",
    "batales",
    "bromeliales",
    "bryales",
    "buxbaumiales",
    "caliciales",
    "callitrichales",
    "calobryales",
    "calycerales",
    "campanulales",
    "cantharellales",
    "capnodiales",
    "capparales",
    "caryophyllales",
    "casuarinales",
    "caulerpales",
    "celastrales",
    "commelinales",
    "cornales",
    "cycadales",
    "cyclanthales",
    "cyperales",
    "diapensiales",
    "dicranales",
    "dilleniales",
    "dipsacales",
    "dothideales",
    "ebenales",
    "ephedrales",
    "equisetales",
    "ericales",
    "eriocaulales",
    "euphorbiales",
    "eurotiales",
    "fabales",
    "fagales",
    "fissidentales",
    "funariales",
    "gentianales",
    "geraniales",
    "ginkgoales",
    "gnetales",
    "gracilariales",
    "graphidales",
    "grimmiales",
    "gyalectales",
    "haloragales",
    "halymeniales",
    "hamamelidales",
    "hookeriales",
    "hydrocharitales",
    "hydropteridales",
    "hypnales",
    "hypocreales",
    "illiciales",
    "isobryales",
    "isoetales",
    "juglandales",
    "juncales",
    "jungermanniales",
    "lamiales",
    "laurales",
    "lecanorales",
    "lecythidales",
    "leitneriales",
    "leotiales",
    "leucodontales",
    "lichinales",
    "liliales",
    "linales",
    "lycopodiales",
    "magnoliales",
    "malvales",
    "marattiales",
    "marchantiales",
    "melanommatales",
    "metzgeriales",
    "myricales",
    "myrtales",
    "najadales",
    "nepenthales",
    "nymphaeales",
    "onygenales",
    "opegraphales",
    "ophioglossales",
    "orchidales",
    "orthotrichales",
    "ostropales",
    "pandanales",
    "papaverales",
    "patellariales",
    "peltigerales",
    "pertusariales",
    "phyllachorales",
    "pinales",
    "piperales",
    "plantaginales",
    "platygloeales",
    "pleosporales",
    "plumbaginales",
    "podostemales",
    "polygalales",
    "polygonales",
    "polypodiales",
    "polytrichales",
    "pottiales",
    "primulales",
    "proteales",
    "psilotales",
    "pyrenulales",
    "rafflesiales",
    "ranunculales",
    "restionales",
    "rhamnales",
    "rhizophorales",
    "rosales",
    "rubiales",
    "salicales",
    "santalales",
    "sapindales",
    "schistostegiales",
    "scrophulariales",
    "selaginellales",
    "seligerales",
    "solanales",
    "sordariales",
    "sphaeriales",
    "sphaerocarpales",
    "sphagnales",
    "stereales",
    "taxales",
    "teloschistales",
    "tetraphidales",
    "theales",
    "tremellales",
    "triuridales",
    "typhales",
    "ulvales",
    "urticales",
    "verrucariales",
    "violales",
    "zingiberales"
]
PLANT_COMMON_FAMILY_NAMES = [
    "acanthus",
    "achatocarpus",
    "adder's-tongue",
    "aloe",
    "amaranth",
    "araucaria",
    "arrow-grass",
    "arum",
    "aster",
    "azolla",
    "balanophora",
    "banana",
    "barbados cherry",
    "barberry",
    "basella",
    "bayberry",
    "beech",
    "begonia",
    "bellflower",
    "birch",
    "bird of paradise flower",
    "birthwort",
    "bittersweet",
    "bladdernut",
    "bladderwort",
    "bloodwort",
    "borage",
    "boxwood",
    "bracken fern",
    "brazil-nut",
    "bromeliad",
    "broom-rape",
    "brunellia",
    "buckbean",
    "buckthorn",
    "buckwheat",
    "burmannia",
    "bur-reed",
    "buttercup",
    "butterfly-bush",
    "cacao",
    "cactus",
    "calamus",
    "calycera",
    "canella",
    "canna",
    "cannarus",
    "cape-pondweed",
    "caper",
    "carpet-weed",
    "carrot",
    "catbrier",
    "catkin-mistletoe",
    "cat-tail",
    "cecropia",
    "century-plant",
    "chain fern",
    "chinese gooseberry",
    "chloranthus",
    "christmas mistletoe",
    "clethra",
    "climbing fern",
    "club-moss",
    "coca",
    "cocoa-plum",
    "corkwood",
    "costus",
    "creosote-bush",
    "crossosoma",
    "crowberry",
    "cucumber",
    "cunonia",
    "curly-grass",
    "currant",
    "custard-apple",
    "cycad",
    "cypress",
    "cyrilla",
    "datisca",
    "diamond-leaf fern",
    "diapensia",
    "dillenia",
    "ditch-grass",
    "dodder",
    "dogbane",
    "dogwood",
    "duckweed",
    "east indian pitcher-plant",
    "ebony",
    "eel-grass",
    "elaeocarpus",
    "elm",
    "epacris",
    "evening primrose",
    "fig-marigold",
    "figwort",
    "filmy fern",
    "flacourtia",
    "flagellaria",
    "flax",
    "floating fern",
    "flowering fern",
    "flowering rush",
    "forking fern",
    "four o'clock",
    "frankenia",
    "frankincense",
    "fumitory",
    "gentian",
    "geranium",
    "gesneriad",
    "ginger",
    "ginkgo",
    "ginseng",
    "gnetum",
    "goodenia",
    "goosefoot",
    "grape",
    "grass",
    "greyia",
    "gunnera",
    "hanging fern",
    "hanguana",
    "heath",
    "heliconia",
    "hemp",
    "hernandia",
    "hippocratea",
    "holly",
    "honeysuckle",
    "horned pondweed",
    "hornwort",
    "horse-chestnut",
    "horse-radish tree",
    "horsetail",
    "hydrangea",
    "icacina",
    "indian almond",
    "indian pipe",
    "iris",
    "joinvillea",
    "jojoba",
    "kapok-tree",
    "karaka",
    "katsura-tree",
    "kihi fern",
    "krameria",
    "lardizabala",
    "laurel",
    "leadwort",
    "lennoa",
    "lily",
    "linden",
    "lipstick-tree",
    "lizard's-tail",
    "loasa",
    "logania",
    "loosestrife",
    "lotus-lily",
    "madder",
    "magnolia",
    "mahogany",
    "maidenhair fern",
    "mallow",
    "manatee-grass",
    "mangosteen",
    "maple",
    "mare's-tail",
    "marsh fern",
    "mayaca",
    "meadow-foam",
    "melastome",
    "melianthus",
    "meranti",
    "mezereum",
    "mignonette",
    "milkweed",
    "milkwort",
    "mint",
    "monimia",
    "moonseed",
    "mormon-tea",
    "morning-glory",
    "moschatel",
    "mulberry",
    "mustard",
    "myoporum",
    "myrsine",
    "myrtle",
    "nasturtium",
    "nettle",
    "nutmeg",
    "ochna",
    "ocotillo",
    "olax",
    "oleaster",
    "olive",
    "orchid",
    "palm",
    "panama hat",
    "papaya",
    "passion-flower",
    "pea",
    "peony",
    "pepper",
    "philydraceae",
    "phlox",
    "pine",
    "pink",
    "pipewort",
    "pitcher-plant",
    "pittosporum",
    "plane-tree",
    "plantain",
    "plum yew",
    "podocarpus",
    "pokeweed",
    "polypody",
    "pomegranate",
    "pondweed",
    "poppy",
    "posidonia",
    "potato",
    "prayer-plant",
    "primrose",
    "protea",
    "purslane",
    "quassia",
    "quillwort",
    "rafflesia",
    "red mangrove",
    "river-weed",
    "rock-rose",
    "rose",
    "royal fern",
    "rue",
    "rush",
    "sabia",
    "sago-palm",
    "saltwort",
    "sandalwood",
    "sapodilla",
    "saxifrage",
    "scheuchzeria",
    "schisandra",
    "screw-pine",
    "sedge",
    "sesame",
    "she-oak",
    "shingle plant",
    "shinleaf",
    "shoestring fern",
    "showy mistletoe",
    "silk tassel",
    "soapberry",
    "sonneratia",
    "souari",
    "spenoclea",
    "spiderwort",
    "spike-moss",
    "spleenwort",
    "spurge",
    "stackhousia",
    "star-anise",
    "stemona",
    "stonecrop",
    "storax",
    "strawberry-shrub",
    "sumac",
    "sundew",
    "suriana",
    "sweetleaf",
    "tacca",
    "tamarix",
    "tape-grass",
    "tea",
    "teasel",
    "theophrasta",
    "touch-me-not",
    "tree fern",
    "tree fern",
    "triurus",
    "trumpet-creeper",
    "turnera",
    "valerian",
    "verbena",
    "vessel fern",
    "violet",
    "walnut",
    "water chestnut",
    "water fern",
    "water milfoil",
    "water-clover",
    "water-hyacinth",
    "waterleaf",
    "water-lily",
    "water-nymph",
    "water-plantain",
    "water-poppy",
    "water-shield",
    "water-starwort",
    "waterwort",
    "whisk-fern",
    "willow",
    "wintera",
    "witch-hazel",
    "wood fern",
    "wood-sorrel",
    "yam",
    "yellow-eyed grass",
    "yew",
]
